services:
  hapi-fhir-server:
    build: .
    container_name: hapi-fhir-server
    restart: on-failure
    ports:
      - "8080:8080"
  hapi-fhir-postgres:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - hapi-fhir-postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "cshe882@csh.org.tw"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    restart: always
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: "admin"
      SINGLE_USER_CREDENTIALS_PASSWORD: "1qaz2wsx3edc4rfv"
      NIFI_WEB_HTTPS_PORT: "8443"
      NIFI_WEB_PROXY_HOST: "192.168.0.65:8443"
    ports:
      - "8443:8443"
volumes:
  hapi-fhir-postgres: